### ISSUE TITLE
Luego de hacer logout hacer refresh 

### ISSUE THREAD

**Issue by mvinan** [Silverhill/coupon-maker-frontend#34]

**Comment by fabricioflores** [comment]
xq? no basta con quitar de local storage y redirigirlo?

**Comment by mvinan** [comment]
:lenin: asi esta actualmente, pero si me logueo de nuevo con otro usuario, me muestra la información del usuario anterior, `too weird`, looks like `cache`

**Comment by leninkp** [comment]
cerrador por confusion
